Repository astro-informatics/s2fft, pull requests merged in 2024-11, with the labels that each got.

#239 add custom collective transforms
  docs/api/precompute_transforms/custom_ops.rst
  docs/api/precompute_transforms/index.rst
  docs/index.rst
  s2fft/precompute_transforms/__init__.py
  s2fft/precompute_transforms/custom_ops.py
  s2fft/precompute_transforms/fourier_wigner.py
  tests/test_fourier_wigner.py
  tests/test_lifting_transforms.py
Labels: enhancement, blocker

#213 Use codecov-action in place of manual upload
  .github/workflows/tests.yml
  pyproject.toml
Labels: infrastructure

#236 Update citation details in docs and add CITATION.cff file
  .pip_readme.rst
  CITATION.cff
  README.md
  docs/index.rst
Labels: documentation

#235 Add workflow for building wheels and publishing releases to PyPI
  .github/workflows/build.yml
Labels: infrastructure

#210 Update test matrix and add scheduled tests
  .github/workflows/tests.yml
Labels: infrastructure
