Repository astro-informatics/s2fft, pull requests merged in 2024-10, with the labels that each got.

#234 Add configuration for automatic release notes
  .github/release.yml
Labels: infrastructure

#230 Add stable high-spin transforms (precompute, standard)
  README.md
  docs/api/precompute_transforms/index.rst
  s2fft/precompute_transforms/construct.py
  s2fft/recursions/risbo.py
  s2fft/recursions/risbo_jax.py
  tests/test_spherical_precompute.py
  tests/test_wigner_precompute.py
  tests/test_wigner_recursions.py
Labels: documentation, enhancement, critical

#238 add stable forward/inverse memory efficient Wigner transforms
  docs/api/precompute_transforms/fourier_wigner.rst
  docs/api/precompute_transforms/index.rst
  s2fft/precompute_transforms/__init__.py
  s2fft/precompute_transforms/construct.py
  s2fft/precompute_transforms/fourier_wigner.py
  s2fft/precompute_transforms/wigner.py
  tests/test_fourier_wigner.py
Labels: enhancement
